#
# Build our container that runs Splunk Lab with the Telegram app addin
#

FROM dmuth1/splunk-lab

RUN wget https://s3.amazonaws.com/dmuth-splunk-lab/nlp-text-analytics_102.tgz \
        && tar xfvz nlp-text-analytics_102.tgz \
        && mv nlp-text-analytics /opt/splunk/etc/apps/ \
        && rm -fv /tmp/nlp-text-analytics_102.tgz 

#
# Copy in our application
#
COPY splunk-app/ /opt/splunk/etc/apps/splunk-telegram


